package Home;

//Excel


import Conexion.Crud;
import Controlador.ControladorExcel;
import Controlador.ControladorExcel1;
import Hora.Hora;
import Modelo.ModeloExcel;
import Objetos.Costos;
import java.awt.Color;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Date;
import static javax.management.Query.value;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;



public class Costos_Lista extends javax.swing.JFrame {

    //inicializacion de los objetos
    Crud crud1 = new Crud();
    ArrayList<Costos> grupos = new ArrayList<>();

    JButton modificar = new JButton("Modificar");
    JButton eliminar = new JButton("Eliminar");
    Object[][] filas;

    //Metodo constructor
    public Costos_Lista() {

        Date fechaActual = new Date();
        initComponents();
        String fecha1 = fechaActual.getDate() + "/" + fechaActual.getMonth() + 1 + "/" + (fechaActual.getYear() - 100);
        fecha.setText(fecha1);
        this.setLocationRelativeTo(null);

        ConstruirTabla();

    }

    private void ConstruirTabla() {

        Color blanco = new Color(255, 255, 255);
        modificar.setName("m");
        modificar.setBackground(new Color(255, 195, 0));
        modificar.setForeground(blanco);
        modificar.setBorder(BorderFactory.createEmptyBorder());
        eliminar.setName("e");
        eliminar.setBackground(new Color(254, 34, 51));
        eliminar.setForeground(blanco);
        eliminar.setBorder(BorderFactory.createEmptyBorder());
        this.filas = new Object[10][5];

        ObtenerCostos();
        tabla.setDefaultRenderer(Object.class, new Render());
        DefaultTableModel modelo = new DefaultTableModel(
                this.filas,
                new Object[]{"Id", "Nombre", "Cantidad", "", ""}
        ) {
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        };
        tabla.setModel(modelo);

        DefaultTableCellRenderer t = new DefaultTableCellRenderer();
        t.setBackground(Color.red);
    }

    //
    private void ObtenerCostos() {
        int contador = 0;
        ArrayList<Costos> costos = new ArrayList<>();
        costos = crud1.getCostos();
        //Recorridos de los grupos
        for (Costos c : costos) {
            if (c.getNombre().equals("Inscripcion") || c.getNombre().equals("Colegiatura")|| c.getNombre().equals("Reinscripcion")) {
                this.filas[contador][0] = (Object) c.getIdCostos();
                this.filas[contador][1] = (Object) c.getNombre();
                this.filas[contador][2] = (Object) c.getCantidad();
                this.filas[contador][3] = (Object) modificar;
            } else {
                this.filas[contador][0] = (Object) c.getIdCostos();
                this.filas[contador][1] = (Object) c.getNombre();
                this.filas[contador][2] = (Object) c.getCantidad();
                this.filas[contador][3] = (Object) modificar;
                this.filas[contador][4] = (Object) eliminar;
            }
            contador++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAlumnos = new javax.swing.JButton();
        puntero1 = new javax.swing.JLabel();
        btnAlumnos2 = new javax.swing.JButton();
        btnAlumnos3 = new javax.swing.JButton();
        btnAlumnos4 = new javax.swing.JButton();
        btnAlumnos5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        fecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAlumnos7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        exportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(185, 187, 189));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAlumnos.setBackground(new java.awt.Color(255, 255, 255));
        btnAlumnos.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        btnAlumnos.setForeground(new java.awt.Color(185, 187, 189));
        btnAlumnos.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/user-2.png")); // NOI18N
        btnAlumnos.setText("Alumnos");
        btnAlumnos.setBorderPainted(false);
        btnAlumnos.setContentAreaFilled(false);
        btnAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit(evt);
            }
        });
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });

        puntero1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        puntero1.setForeground(new java.awt.Color(255, 255, 255));

        btnAlumnos2.setBackground(new java.awt.Color(255, 255, 255));
        btnAlumnos2.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        btnAlumnos2.setForeground(new java.awt.Color(185, 187, 189));
        btnAlumnos2.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/inscripcion.png")); // NOI18N
        btnAlumnos2.setText("Inscripciones");
        btnAlumnos2.setBorderPainted(false);
        btnAlumnos2.setContentAreaFilled(false);
        btnAlumnos2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlumnos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enter2(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit2(evt);
            }
        });
        btnAlumnos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnos2ActionPerformed(evt);
            }
        });

        btnAlumnos3.setBackground(new java.awt.Color(255, 255, 255));
        btnAlumnos3.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        btnAlumnos3.setForeground(new java.awt.Color(185, 187, 189));
        btnAlumnos3.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/multitud.png")); // NOI18N
        btnAlumnos3.setText("Grupos");
        btnAlumnos3.setBorderPainted(false);
        btnAlumnos3.setContentAreaFilled(false);
        btnAlumnos3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlumnos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlumnos3enter2(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlumnos3exit2(evt);
            }
        });
        btnAlumnos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnos3ActionPerformed(evt);
            }
        });

        btnAlumnos4.setBackground(new java.awt.Color(255, 255, 255));
        btnAlumnos4.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        btnAlumnos4.setForeground(new java.awt.Color(57, 176, 253));
        btnAlumnos4.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/dar-dinero.png")); // NOI18N
        btnAlumnos4.setText("Cuotas");
        btnAlumnos4.setBorderPainted(false);
        btnAlumnos4.setContentAreaFilled(false);
        btnAlumnos4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlumnos4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlumnos4enter2(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlumnos4exit2(evt);
            }
        });
        btnAlumnos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnos4ActionPerformed(evt);
            }
        });

        btnAlumnos5.setBackground(new java.awt.Color(255, 255, 255));
        btnAlumnos5.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        btnAlumnos5.setForeground(new java.awt.Color(185, 187, 189));
        btnAlumnos5.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/conocimiento.png")); // NOI18N
        btnAlumnos5.setText(" Colegiatura");
        btnAlumnos5.setBorderPainted(false);
        btnAlumnos5.setContentAreaFilled(false);
        btnAlumnos5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlumnos5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlumnos5enter2(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlumnos5exit2(evt);
            }
        });
        btnAlumnos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnos5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jLabel1.setText("Menu");

        salir.setBackground(new java.awt.Color(255, 255, 255));
        salir.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(185, 187, 189));
        salir.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/button.png")); // NOI18N
        salir.setText("Salir");
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirExit(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(puntero1)
                .addGap(239, 239, 239))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlumnos2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlumnos5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlumnos4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAlumnos3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puntero1)
                .addGap(18, 18, 18)
                .addComponent(btnAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlumnos2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlumnos5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlumnos4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlumnos3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 611));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        fecha.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/calendar.png")); // NOI18N
        fecha.setText("31/02/22");

        jLabel2.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel2.setText("Bienvenido Angel Garcia");

        jLabel3.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jLabel3.setText("Director");

        jLabel4.setFont(new java.awt.Font("Raanana", 1, 24)); // NOI18N
        jLabel4.setText("Preparatoria Justo Sierra");

        btnAlumnos7.setBackground(new java.awt.Color(255, 255, 255));
        btnAlumnos7.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        btnAlumnos7.setForeground(new java.awt.Color(185, 187, 189));
        btnAlumnos7.setBorderPainted(false);
        btnAlumnos7.setContentAreaFilled(false);
        btnAlumnos7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlumnos7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlumnos7enter2(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlumnos7exit2(evt);
            }
        });
        btnAlumnos7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnos7ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/check.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(165, 165, 165)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAlumnos7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha)
                    .addComponent(jLabel4))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlumnos7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 730, 120));

        jPanel2.setBackground(new java.awt.Color(241, 241, 241));

        panelTabla.setBackground(new java.awt.Color(255, 255, 255));

        tabla.setFont(new java.awt.Font("Malayalam MN", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {"", null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Title 3"
            }
        ));
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabla.setRowHeight(27);
        tabla.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        exportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel-2.png"))); // NOI18N
        exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exportar)
                .addGap(28, 28, 28))
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exportar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 730, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void enter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter
        btnAlumnos.setForeground(new Color(57, 176, 253));
        puntero1.setForeground(new Color(57, 176, 253));
    }//GEN-LAST:event_enter

    private void exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit
        btnAlumnos.setForeground(new Color(185, 187, 189));
        puntero1.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_exit

    private void btnAlumnos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnos2ActionPerformed
        // TODO add your handling code here:
        Inscripciones_Menu menu = new Inscripciones_Menu();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_btnAlumnos2ActionPerformed

    private void enter2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter2
        btnAlumnos2.setForeground(new Color(57, 176, 253));

    }//GEN-LAST:event_enter2

    private void exit2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2
        btnAlumnos2.setForeground(new Color(185, 187, 189));
    }//GEN-LAST:event_exit2

    private void btnAlumnos3enter2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos3enter2
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAlumnos3enter2

    private void btnAlumnos3exit2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos3exit2
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAlumnos3exit2

    private void btnAlumnos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnos3ActionPerformed
        // TODO add your handling code here:
        Grupos_Menu g = new Grupos_Menu();
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAlumnos3ActionPerformed

    private void btnAlumnos4enter2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos4enter2
        // TODO add your handling code here:
        btnAlumnos4.setForeground(new Color(57, 176, 253));
    }//GEN-LAST:event_btnAlumnos4enter2

    private void btnAlumnos4exit2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos4exit2
        // TODO add your handling code here:
        btnAlumnos4.setForeground(new Color(185, 187, 189));
    }//GEN-LAST:event_btnAlumnos4exit2

    private void btnAlumnos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnos4ActionPerformed
        // TODO add your handling code here:
        Costos_Menu c = new Costos_Menu();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAlumnos4ActionPerformed

    private void btnAlumnos5enter2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos5enter2

    }//GEN-LAST:event_btnAlumnos5enter2

    private void btnAlumnos5exit2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos5exit2
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAlumnos5exit2

    private void btnAlumnos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnos5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlumnos5ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void btnAlumnos7enter2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos7enter2
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlumnos7enter2

    private void btnAlumnos7exit2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos7exit2
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlumnos7exit2

    private void btnAlumnos7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnos7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlumnos7ActionPerformed

    private void SalirEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirEnter
        // TODO add your handling code here:
        salir.setForeground(new Color(250, 41, 41));
    }//GEN-LAST:event_SalirEnter

    private void SalirExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirExit
        // TODO add your handling code here:
        salir.setForeground(new Color(185, 187, 189));
    }//GEN-LAST:event_SalirExit


    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int columna = tabla.getColumnModel().getColumnIndexAtX(evt.getX());
        int fila = evt.getY() / tabla.getRowHeight();

        if (fila < tabla.getRowCount() && fila >= 0 && columna < tabla.getColumnCount() && columna >= 0) {
            Object valor = tabla.getValueAt(fila, columna);
            if (valor instanceof JButton) {
                ((JButton) valor).doClick();
                JButton boton = (JButton) valor;
                int id = (int) tabla.getValueAt(fila, 0);
                String nombre = (String) tabla.getValueAt(fila, 1);
                String cantidad = (String) tabla.getValueAt(fila, 2);
                if (boton.getName().equals("m")) {
                    Costos_Nuevo g = new Costos_Nuevo(id, "Modificar", nombre, cantidad);
                    g.setVisible(true);
                    this.setVisible(false);
                } else if (boton.getName().equals("e")) {
                    crud1.deleteCosto(id);
                    this.ConstruirTabla();
                }
            }
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarActionPerformed
        // TODO add your handling code here:
        ModeloExcel modeloE = new ModeloExcel();
        ControladorExcel1 contraControladorExcel = new ControladorExcel1(this, modeloE);
        
    }//GEN-LAST:event_exportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Costos_Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Costos_Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Costos_Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Costos_Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Costos_Lista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JButton btnAlumnos2;
    private javax.swing.JButton btnAlumnos3;
    private javax.swing.JButton btnAlumnos4;
    private javax.swing.JButton btnAlumnos5;
    private javax.swing.JButton btnAlumnos7;
    public javax.swing.JButton exportar;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JLabel puntero1;
    private javax.swing.JButton salir;
    public javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
