package Home;



import Hora.Hora;
import java.awt.Color;
import java.util.Date;

public class Costos_Menu extends javax.swing.JFrame {

    //Metodo constructor
    public Costos_Menu() {
        Date fechaActual=new Date();
        initComponents();
        String fecha1=fechaActual.getDate()+"/"+fechaActual.getMonth()+1+"/"+(fechaActual.getYear()-100);
        fecha.setText(fecha1);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAlumnos = new javax.swing.JButton();
        puntero1 = new javax.swing.JLabel();
        btnAlumnos2 = new javax.swing.JButton();
        btnAlumnos3 = new javax.swing.JButton();
        cuotas = new javax.swing.JButton();
        colegiatura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        btnAlumnos6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        fecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAlumnos7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nuevo = new javax.swing.JButton();
        pendientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(185, 187, 189));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAlumnos.setBackground(new java.awt.Color(255, 255, 255));
        btnAlumnos.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        btnAlumnos.setForeground(new java.awt.Color(185, 187, 189));
        btnAlumnos.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/user-2.png")); // NOI18N
        btnAlumnos.setText("Alumnos");
        btnAlumnos.setBorderPainted(false);
        btnAlumnos.setContentAreaFilled(false);
        btnAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit(evt);
            }
        });
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });

        puntero1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        puntero1.setForeground(new java.awt.Color(255, 255, 255));

        btnAlumnos2.setBackground(new java.awt.Color(255, 255, 255));
        btnAlumnos2.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        btnAlumnos2.setForeground(new java.awt.Color(185, 187, 189));
        btnAlumnos2.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/inscripcion.png")); // NOI18N
        btnAlumnos2.setText("Inscripciones");
        btnAlumnos2.setBorderPainted(false);
        btnAlumnos2.setContentAreaFilled(false);
        btnAlumnos2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlumnos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enter2(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit2(evt);
            }
        });
        btnAlumnos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnos2ActionPerformed(evt);
            }
        });

        btnAlumnos3.setBackground(new java.awt.Color(255, 255, 255));
        btnAlumnos3.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        btnAlumnos3.setForeground(new java.awt.Color(185, 187, 189));
        btnAlumnos3.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/multitud.png")); // NOI18N
        btnAlumnos3.setText("Grupos");
        btnAlumnos3.setBorderPainted(false);
        btnAlumnos3.setContentAreaFilled(false);
        btnAlumnos3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlumnos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlumnos3enter2(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlumnos3exit2(evt);
            }
        });
        btnAlumnos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnos3ActionPerformed(evt);
            }
        });

        cuotas.setBackground(new java.awt.Color(255, 255, 255));
        cuotas.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        cuotas.setForeground(new java.awt.Color(57, 176, 253));
        cuotas.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/dar-dinero.png")); // NOI18N
        cuotas.setText("Cuotas");
        cuotas.setBorderPainted(false);
        cuotas.setContentAreaFilled(false);
        cuotas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cuotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cuotasenter2(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cuotasexit2(evt);
            }
        });
        cuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuotasActionPerformed(evt);
            }
        });

        colegiatura.setBackground(new java.awt.Color(255, 255, 255));
        colegiatura.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        colegiatura.setForeground(new java.awt.Color(185, 187, 189));
        colegiatura.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/conocimiento.png")); // NOI18N
        colegiatura.setText(" Colegiatura");
        colegiatura.setBorderPainted(false);
        colegiatura.setContentAreaFilled(false);
        colegiatura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        colegiatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colegiaturaenter2(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colegiaturaexit2(evt);
            }
        });
        colegiatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colegiaturaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jLabel1.setText("Menu");

        salir.setBackground(new java.awt.Color(255, 255, 255));
        salir.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(185, 187, 189));
        salir.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/button.png")); // NOI18N
        salir.setText("Salir");
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirExit(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        btnAlumnos6.setBackground(new java.awt.Color(255, 255, 255));
        btnAlumnos6.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        btnAlumnos6.setForeground(new java.awt.Color(185, 187, 189));
        btnAlumnos6.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/configuraciones.png")); // NOI18N
        btnAlumnos6.setText("Configuracion");
        btnAlumnos6.setBorderPainted(false);
        btnAlumnos6.setContentAreaFilled(false);
        btnAlumnos6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlumnos6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlumnos6enter2(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlumnos6exit2(evt);
            }
        });
        btnAlumnos6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnos6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(puntero1)
                .addGap(239, 239, 239))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAlumnos3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlumnos2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(colegiatura, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlumnos6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puntero1)
                .addGap(18, 18, 18)
                .addComponent(btnAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlumnos2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(colegiatura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlumnos3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlumnos6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 611));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        fecha.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/calendar.png")); // NOI18N
        fecha.setText("31/02/22");

        jLabel2.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel2.setText("Bienvenido Angel Garcia");

        jLabel3.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jLabel3.setText("Director");

        jLabel4.setFont(new java.awt.Font("Raanana", 1, 24)); // NOI18N
        jLabel4.setText("Preparatoria Justo Sierra");

        btnAlumnos7.setBackground(new java.awt.Color(255, 255, 255));
        btnAlumnos7.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        btnAlumnos7.setForeground(new java.awt.Color(185, 187, 189));
        btnAlumnos7.setBorderPainted(false);
        btnAlumnos7.setContentAreaFilled(false);
        btnAlumnos7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlumnos7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlumnos7enter2(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlumnos7exit2(evt);
            }
        });
        btnAlumnos7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnos7ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/check.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(165, 165, 165)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAlumnos7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha)
                    .addComponent(jLabel4))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlumnos7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 730, 120));

        jPanel2.setBackground(new java.awt.Color(241, 241, 241));

        nuevo.setBackground(new java.awt.Color(255, 255, 255));
        nuevo.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        nuevo.setForeground(new java.awt.Color(185, 187, 189));
        nuevo.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/desktop-computer-3.png")); // NOI18N
        nuevo.setText("Nuevo");
        nuevo.setBorderPainted(false);
        nuevo.setContentAreaFilled(false);
        nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevo.setOpaque(true);
        nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nuevoenter2(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nuevoexit2(evt);
            }
        });
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        pendientes.setBackground(new java.awt.Color(255, 255, 255));
        pendientes.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        pendientes.setForeground(new java.awt.Color(185, 187, 189));
        pendientes.setIcon(new javax.swing.ImageIcon("/Users/edgarivanlorenzovillalobos/NetBeansProjects/Justo_Sierra/src/Imagenes/fijo.png")); // NOI18N
        pendientes.setText("Lista");
        pendientes.setBorderPainted(false);
        pendientes.setContentAreaFilled(false);
        pendientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pendientes.setOpaque(true);
        pendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pendientesenter2(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pendientesexit2(evt);
            }
        });
        pendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(pendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 730, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void enter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter
        btnAlumnos.setForeground(new Color(57, 176, 253  ));
        puntero1.setForeground(new Color(57, 176, 253));
    }//GEN-LAST:event_enter

    private void exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit
        btnAlumnos.setForeground(new Color(185,187,189 ));
        puntero1.setForeground(new Color(255, 255, 255   ));
    }//GEN-LAST:event_exit

    private void btnAlumnos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnos2ActionPerformed
        // TODO add your handling code here:
        Inscripciones_Menu menu=new Inscripciones_Menu();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_btnAlumnos2ActionPerformed

    private void enter2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter2
       btnAlumnos2.setForeground(new Color(57, 176, 253  ));
      
    }//GEN-LAST:event_enter2

    private void exit2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2
        btnAlumnos2.setForeground(new Color(185,187,189));
    }//GEN-LAST:event_exit2

    private void btnAlumnos3enter2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos3enter2
        // TODO add your handling code here:
        btnAlumnos3.setForeground(new Color(57, 176, 253  ));
    }//GEN-LAST:event_btnAlumnos3enter2

    private void btnAlumnos3exit2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos3exit2
        // TODO add your handling code here:
       btnAlumnos3.setForeground(new Color(185,187,189));
    }//GEN-LAST:event_btnAlumnos3exit2

    private void btnAlumnos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlumnos3ActionPerformed

    private void cuotasenter2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuotasenter2
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cuotasenter2

    private void cuotasexit2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuotasexit2
        
    }//GEN-LAST:event_cuotasexit2

    private void cuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuotasActionPerformed
        // TODO add your handling code here:
        Costos_Menu c=new Costos_Menu();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cuotasActionPerformed

    private void colegiaturaenter2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colegiaturaenter2
        colegiatura.setForeground(new Color(57, 176, 253  ));
    }//GEN-LAST:event_colegiaturaenter2

    private void colegiaturaexit2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colegiaturaexit2
        // TODO add your handling code here:
        colegiatura.setForeground(new Color(185,187,189));
    }//GEN-LAST:event_colegiaturaexit2

    private void colegiaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colegiaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colegiaturaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void btnAlumnos7enter2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos7enter2
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlumnos7enter2

    private void btnAlumnos7exit2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos7exit2
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlumnos7exit2

    private void btnAlumnos7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnos7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlumnos7ActionPerformed

    private void SalirEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirEnter
        // TODO add your handling code here:
        salir.setForeground(new Color(250, 41, 41  ));
    }//GEN-LAST:event_SalirEnter

    private void SalirExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirExit
        // TODO add your handling code here:
        salir.setForeground(new Color(185,187,189));
    }//GEN-LAST:event_SalirExit

    private void pendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendientesActionPerformed
        // TODO add your handling code here:
        Costos_Lista nuevo=new Costos_Lista();
        this.setVisible(false);
        nuevo.setVisible(true);
    }//GEN-LAST:event_pendientesActionPerformed

    private void pendientesexit2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendientesexit2
        // TODO add your handling code here:
        pendientes.setForeground(new Color(185,187,189));
    }//GEN-LAST:event_pendientesexit2

    private void pendientesenter2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendientesenter2
        // TODO add your handling code here:
        pendientes.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_pendientesenter2

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
        Costos_Nuevo g=new Costos_Nuevo();
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nuevoActionPerformed

    private void nuevoexit2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoexit2
        // TODO add your handling code here:
        nuevo.setForeground(new Color(185,187,189));
    }//GEN-LAST:event_nuevoexit2

    private void nuevoenter2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoenter2
        // TODO add your handling code here:
        nuevo.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_nuevoenter2

    private void btnAlumnos6enter2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos6enter2
        // TODO add your handling code here:
        
        btnAlumnos6.setForeground(new Color(57,176,253 ));
    }//GEN-LAST:event_btnAlumnos6enter2

    private void btnAlumnos6exit2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnos6exit2
        // TODO add your handling code here:
        btnAlumnos6.setForeground(new Color(185,187,189));
    }//GEN-LAST:event_btnAlumnos6exit2

    private void btnAlumnos6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnos6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlumnos6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Costos_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Costos_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Costos_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Costos_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Costos_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JButton btnAlumnos2;
    private javax.swing.JButton btnAlumnos3;
    private javax.swing.JButton btnAlumnos6;
    private javax.swing.JButton btnAlumnos7;
    private javax.swing.JButton colegiatura;
    private javax.swing.JButton cuotas;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton nuevo;
    private javax.swing.JButton pendientes;
    private javax.swing.JLabel puntero1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
